#!/usr/bin/env python3
"""Generate harness/macros.tsv from reference/valkey/src/**/*.h.

Thin wrapper over port-harness/lib/analyzers/c_extractor.py. Produces a
row per `#define` with a suggested Rust mapping where the pattern is
obvious (cast macros, type predicates, constants, simple aliases) and
TODO otherwise.

The architect refines specific rows during translation; this is a
first-cut that prevents agents from re-deriving every macro per file.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "reference" / "valkey" / "src"
OUTPUT = ROOT / "harness" / "macros.tsv"
CHASSIS_LIB = ROOT.parent / "port-harness" / "lib" / "analyzers"

sys.path.insert(0, str(CHASSIS_LIB))
import c_extractor as ce  # noqa: E402


# Heuristics for auto-suggesting Rust mapping. Order matters: first hit wins.
# Each entry: (regex over macro body, "rust_mapping_template", "category")
# Variables in templates: {name} = macro name (lowercased), {body} = body text.
HEURISTICS = [
    # Integer constants: `#define X 42` or `#define X 0xff`
    (re.compile(r"^\s*-?\d+\s*$"),         "pub const {name_upper}: i64 = {body};",    "constant"),
    (re.compile(r"^\s*0x[0-9a-fA-F]+\s*$"), "pub const {name_upper}: u64 = {body};",   "constant"),
    # String literal constant
    (re.compile(r'^\s*"[^"]*"\s*$'),       'pub const {name_upper}: &[u8] = b{body};', "constant"),
    # Simple aliases (object-like macro pointing at an identifier)
    (re.compile(r"^\s*[A-Za-z_][A-Za-z0-9_]*\s*$"),
        "pub use crate::{body};  // alias",                                              "alias"),
    # Sizeof: `#define X sizeof(Y)`
    (re.compile(r"^\s*sizeof\s*\(([A-Za-z_][A-Za-z0-9_]*)\)\s*$"),
        "pub const {name_upper}: usize = std::mem::size_of::<???>();  // TODO map type", "sizeof"),
]


def suggest_mapping(macro: ce.Macro) -> tuple[str, str]:
    """Returns (rust_mapping, category)."""
    body = macro.body.strip()
    if not body:
        return ("// (empty body — likely a feature flag; check #ifdef sites)", "flag")
    if macro.is_function_like:
        # Common Valkey patterns
        if re.match(r"^\s*\(\s*\([^)]+\)\s*\)\s*$", body):
            return ("(see C: simple cast — translate at call sites)", "cast")
        if "?" in body and ":" in body:
            return ("(see C: ternary — translate at call sites as `if cond { a } else { b }`)", "ternary")
        # `addReply...` style
        if re.match(r"^\s*add[A-Z]", body):
            return ("(see C: alias for addReply call — use CommandContext.reply_*)", "reply-alias")
        return ("TODO(architect): function-like macro; translate at call site", "function-like")
    # Object-like macro
    for pat, tmpl, cat in HEURISTICS:
        m = pat.match(body)
        if m:
            rendered = tmpl.format(name_upper=macro.name.upper(), body=body)
            return (rendered, cat)
    return ("TODO(architect): see C definition", "complex")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    if not SRC.is_dir():
        print(f"FATAL: {SRC} not found.", file=sys.stderr)
        return 2

    sources = list(ce.walk_sources(SRC, suffix=".h"))
    macros = list(ce.find_macros(sources, root=SRC))
    macros.sort(key=lambda m: (m.file, m.line))

    lines = [
        "# Auto-generated by harness/gen-macros.py from reference/valkey/src/*.h",
        "# DO NOT hand-edit. To refine a row, change HEURISTICS in the generator or",
        "# (preferably) override per-macro by editing harness/macro-overrides.tsv (TODO).",
        "#",
        f"# Total macros: {len(macros)}",
        "# Columns (tab-separated):",
        "#   name              C macro identifier",
        "#   file              header where defined",
        "#   line              line number",
        "#   kind              object | function",
        "#   category          constant | alias | sizeof | cast | ternary | reply-alias | function-like | flag | complex",
        "#   c_body            raw C body (first 80 chars; truncated with ... if longer)",
        "#   rust_mapping      suggested Rust translation (TODO if unclear)",
        "",
    ]
    cat_counts: dict[str, int] = {}
    for m in macros:
        rust_map, cat = suggest_mapping(m)
        cat_counts[cat] = cat_counts.get(cat, 0) + 1
        body_short = m.body if len(m.body) <= 80 else m.body[:77] + "..."
        kind = "function" if m.is_function_like else "object"
        lines.append(ce.emit_tsv_row(m.name, m.file, m.line, kind, cat, body_short, rust_map))

    content = "\n".join(lines) + "\n"

    if args.check:
        old = OUTPUT.read_text() if OUTPUT.exists() else ""
        if old != content:
            print("STALE: harness/macros.tsv", file=sys.stderr)
            return 1
        print(f"OK: macros.tsv in sync ({len(macros)} macros)")
        return 0

    OUTPUT.write_text(content)
    print(f"wrote {OUTPUT.relative_to(ROOT)} ({len(macros)} macros)")
    for cat in sorted(cat_counts):
        print(f"  {cat:<14} {cat_counts[cat]}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
