#!/usr/bin/env python3
"""Generate harness/types.tsv from reference/valkey/src/**/*.{c,h}.

Thin wrapper over port-harness/lib/analyzers/c_extractor.py. Produces a
row per typedef-struct with field-by-field shape, plus a suggested
Rust mapping where the C type aligns with one of our canonical
vocabulary types (per harness/type-vocabulary.tsv).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "reference" / "valkey" / "src"
OUTPUT = ROOT / "harness" / "types.tsv"
VOCAB = ROOT / "harness" / "type-vocabulary.tsv"
CHASSIS_LIB = ROOT.parent / "port-harness" / "lib" / "analyzers"

sys.path.insert(0, str(CHASSIS_LIB))
import c_extractor as ce  # noqa: E402


# Hand-curated mapping from C type names to Rust vocabulary entries.
# Pulled from the type-vocabulary registry + extended with common
# Valkey C types whose Rust home is obvious.
C_TO_RUST = {
    "client":          "Client (crates/redis-core/src/client.rs)",
    "redisDb":         "RedisDb (crates/redis-core/src/db.rs)",
    "robj":            "RedisObject (crates/redis-core/src/object.rs)",
    "sds":             "RedisString (crates/redis-types/src/string.rs)",
    "sdshdr5":         "(internal sds variant — collapse into RedisString)",
    "sdshdr8":         "(internal sds variant — collapse into RedisString)",
    "sdshdr16":        "(internal sds variant — collapse into RedisString)",
    "sdshdr32":        "(internal sds variant — collapse into RedisString)",
    "sdshdr64":        "(internal sds variant — collapse into RedisString)",
    "dict":            "(see redis-ds/dict.rs) — Phase 4",
    "dictEntry":       "(internal — see dict)",
    "list":            "(see redis-ds/adlist.rs) — Phase 4",
    "listNode":        "(internal — see adlist)",
    "listIter":        "(internal — see adlist)",
    "listpack":        "ListPack (crates/redis-ds/src/listpack.rs)",
    "quicklist":       "QuickList (crates/redis-ds/src/quicklist.rs)",
    "ziplist":         "(legacy; superseded by listpack)",
    "intset":          "(internal — see redis-ds/intset.rs)",
    "rax":             "RadixTree (crates/redis-ds/src/rax.rs)",
    "stream":          "Stream (crates/redis-commands/src/stream.rs)",
    "streamCG":        "StreamConsumerGroup (crates/redis-commands/src/stream.rs)",
    "streamID":        "StreamId (crates/redis-ds/src/stream.rs)",
    "zskiplist":       "(internal — see redis-ds/zskiplist.rs)",
    "zskiplistNode":   "(internal — see zskiplist)",
    "zset":            "ZSet (crates/redis-commands/src/zset.rs)",
    "RedisModuleString": "RedisString (alias)",
    "connection":      "Connection enum (crates/redis-core/src/connection.rs) — Phase 3",
    "aeEventLoop":     "EventLoop (crates/redis-core/src/event_loop.rs) — Phase 2 architect decision",
    "multiState":      "MultiState (Client field) — Phase 5",
    "multiCmd":        "(internal — see multi.rs)",
}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    if not SRC.is_dir():
        print(f"FATAL: {SRC} not found.", file=sys.stderr)
        return 2

    sources = list(ce.walk_sources(SRC, suffix=(".c", ".h")))
    typedefs = list(ce.find_struct_typedefs(sources, root=SRC))
    bare = list(ce.find_bare_structs(sources, root=SRC))

    # Dedupe — bare structs sometimes shadow typedefs; prefer typedef.
    seen: dict[str, ce.StructDef] = {}
    for s in typedefs:
        seen[s.name] = s
    for s in bare:
        if s.name not in seen:
            seen[s.name] = s

    structs = sorted(seen.values(), key=lambda s: (s.file, s.line))

    lines = [
        "# Auto-generated by harness/gen-types.py from reference/valkey/src/*.{c,h}",
        "# DO NOT hand-edit. To refine the suggested Rust mapping, change C_TO_RUST",
        "# in the generator. To add new canonical Rust types, edit type-vocabulary.tsv.",
        "#",
        f"# Total struct types: {len(structs)}",
        "# Columns (tab-separated):",
        "#   c_name        C type identifier (typedef name preferred)",
        "#   c_tag         struct tag (when typedef used `struct X { ... } Y;`)",
        "#   file          where defined",
        "#   line          line number",
        "#   n_fields      number of parsed fields",
        "#   fields_brief  first 5 fields as `type:name` (truncated)",
        "#   rust_mapping  suggested Rust type or 'TODO(architect)'",
        "",
    ]

    mapped = 0
    for s in structs:
        mapping = C_TO_RUST.get(s.name, "TODO(architect): assign canonical Rust type")
        if not mapping.startswith("TODO"):
            mapped += 1
        fields_brief = "; ".join(
            f"{t.replace(chr(9), ' ')}:{n}" for (t, n) in s.fields[:5]
        )
        if len(s.fields) > 5:
            fields_brief += "; ..."
        lines.append(ce.emit_tsv_row(
            s.name, s.tag or "", s.file, s.line, len(s.fields), fields_brief, mapping
        ))

    content = "\n".join(lines) + "\n"

    if args.check:
        old = OUTPUT.read_text() if OUTPUT.exists() else ""
        if old != content:
            print("STALE: harness/types.tsv", file=sys.stderr)
            return 1
        print(f"OK: types.tsv in sync ({len(structs)} structs)")
        return 0

    OUTPUT.write_text(content)
    print(f"wrote {OUTPUT.relative_to(ROOT)} ({len(structs)} struct types, {mapped} mapped, {len(structs) - mapped} TODO)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
