#!/usr/bin/env python3
"""Generate harness/error-sites.tsv from reference/valkey/src/**/*.c.

Thin wrapper over port-harness/lib/analyzers/c_extractor.py. Greps the
addReplyError* family of calls + addReplyErrorObject, and emits a row
per call site with a suggested RedisError constructor (per PORTING.md §6.1).

This is the highest-leverage error analysis: the translator looks up
the row for each error site instead of re-deriving the mapping. The
architect refines specific rows when wire-diff catches a mismatch.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "reference" / "valkey" / "src"
OUTPUT = ROOT / "harness" / "error-sites.tsv"
CHASSIS_LIB = ROOT.parent / "port-harness" / "lib" / "analyzers"

sys.path.insert(0, str(CHASSIS_LIB))
import c_extractor as ce  # noqa: E402


# Suggest RedisError constructor based on the first string-literal arg.
# Each pair: (regex against extracted message text, RedisError constructor)
MSG_TO_CONSTRUCTOR = [
    (r"^WRONGTYPE",                         "RedisError::wrong_type()"),
    (r"^wrong number of arguments",         "RedisError::wrong_number_of_args(b\"<cmd>\")"),
    (r"^syntax error",                      "RedisError::syntax(b\"syntax error\")"),
    (r"^value is not an integer",           "RedisError::not_integer()"),
    (r"^value is not a valid float",        "RedisError::not_float()"),
    (r"^value is out of range",             "RedisError::out_of_range()"),
    (r"^NOAUTH",                            "RedisError::no_auth()"),
    (r"^NOPERM",                            "RedisError::no_perm(b\"<scope>\")"),
    (r"^LOADING",                           "RedisError::loading()"),
    (r"^BUSY",                              "RedisError::runtime(b\"BUSY ...\")"),
    (r"^READONLY",                          "RedisError::runtime(b\"READONLY ...\")"),
    (r"^MOVED",                             "RedisError::runtime(b\"MOVED ...\")"),
    (r"^ASK",                               "RedisError::runtime(b\"ASK ...\")"),
    (r"^CLUSTERDOWN",                       "RedisError::runtime(b\"CLUSTERDOWN ...\")"),
    (r"^MASTERDOWN",                        "RedisError::runtime(b\"MASTERDOWN ...\")"),
    (r"^MISCONF",                           "RedisError::runtime(b\"MISCONF ...\")"),
    (r"^OOM",                               "RedisError::runtime(b\"OOM ...\")"),
]


def extract_message(arg_text: str) -> str | None:
    """Pull the first string literal from the arg_text (which is the
    raw bytes between the call's outermost parens)."""
    # arg_text typically: `c, "msg here"` or `c, "msg here", other args`
    m = re.search(r'"((?:\\.|[^"\\])*)"', arg_text)
    if m:
        return m.group(1)
    # `addReplyErrorObject(c, errobj)` — no literal; return None
    return None


def suggest(callee: str, msg: str | None) -> str:
    if callee == "addReplyErrorObject":
        return "RedisError::from_object(errobj)  // see C: caller-supplied error value"
    if msg is None:
        return "TODO(architect): non-literal message; needs RedisError variant"
    for pat, ctor in MSG_TO_CONSTRUCTOR:
        if re.match(pat, msg, flags=re.IGNORECASE):
            return ctor
    # Fallback: generic runtime constructor with the literal
    safe = msg[:60].replace('"', '\\"')
    return f'RedisError::runtime(b"{safe}")'


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    if not SRC.is_dir():
        print(f"FATAL: {SRC} not found.", file=sys.stderr)
        return 2

    sources = list(ce.walk_sources(SRC, suffix=".c"))
    # addReplyError, addReplyErrorFormat, addReplyErrorArity, addReplyErrorObject, etc.
    calls = list(ce.find_function_calls(sources, r"addReplyError\w*", root=SRC))

    lines = [
        "# Auto-generated by harness/gen-error-sites.py from reference/valkey/src/*.c",
        "# DO NOT hand-edit. To refine a row, edit MSG_TO_CONSTRUCTOR in the generator.",
        "#",
        f"# Total error sites: {len(calls)}",
        "# Columns (tab-separated):",
        "#   file              C file",
        "#   line              line number",
        "#   callee            addReplyError, addReplyErrorFormat, addReplyErrorObject, etc.",
        "#   message           extracted string-literal arg (empty if non-literal or *Object)",
        "#   constructor       suggested RedisError constructor",
        "#   context           full source line for the call",
        "",
    ]

    matched = 0
    for c in sorted(calls, key=lambda c: (c.file, c.line)):
        msg = extract_message(c.arg_text)
        ctor = suggest(c.callee, msg)
        if not ctor.startswith("TODO"):
            matched += 1
        lines.append(ce.emit_tsv_row(
            c.file, c.line, c.callee, msg or "", ctor, c.context_line.strip()
        ))

    content = "\n".join(lines) + "\n"

    if args.check:
        old = OUTPUT.read_text() if OUTPUT.exists() else ""
        if old != content:
            print("STALE: harness/error-sites.tsv", file=sys.stderr)
            return 1
        print(f"OK: error-sites.tsv in sync ({len(calls)} sites)")
        return 0

    OUTPUT.write_text(content)
    print(f"wrote {OUTPUT.relative_to(ROOT)} ({len(calls)} call sites, {matched} resolved, {len(calls) - matched} TODO)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
